#214316 Bugfix for wrong cart qty after coming back from external-checkout (#486)
This behavior is caused by multiple problems:
* We didn't clear the cart before we reassign the session – this leads into a merge of the same cart into the existing one after the generic login in the VSF. I also disabled the `sync` parameter for the `cart/clear` action in `user/startSessionWithToken` as we don't need it and it might ends in conflicts with congruent requests.
* I removed the `vsf_token_quote ` cookie logic as we don't need this anymore. The user is logged in if the  `vsf_token_customer` cookie is set and will load the quote after login.
* Prevent a `TypeError: result.forEach is not a function` error notification on add-to-cart actions when the request returns an error. This was caused by a custom `cartHooks.beforeSync` hook and its `cart/updateFreeCartItems` action which might receive as error-message-string instead an array.
* Bugfix for `cart/mergeServerItem` method which adds cart-items asynchronously. When you logged in inside the external-checkout and then went back to the VSF, the cart is first emptied and then merged correctly into another. But at the end the wrong `cartItemsHash`  is saved to the local-storage. This causes that, at the next reload, the cart is merged with itself because it thinks `isSyncRequired` and `mergeQty` in the `cart/connect` action are `true`. The wrong `cartItemsHash` is saved because the VSF wouldn't wait for the async `addItem` action in `mergeServerItem`.

It's connected with the problems of #480